{% set name = "lpips" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/richzhang/PerceptualSimilarity/archive/{{ version }}.tar.gz
  sha256: 5e59cf9c3204c975f870dfc36591b1da0aaf0ef600a0347d4a00f8daf15b3f0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python  >=3.6
  run:
    - python  >=3.6
    - numpy
    - pytorch  >=0.4.0
    - torchvision
    - scipy
    - scikit-image  >=0.13.0
    - opencv  >=2.4.11
    - matplotlib-base  >=1.5.1
    - tqdm  >=4.28.1
    - jupyter

test:
  imports:
    - lpips

about:
  home: https://github.com/richzhang/PerceptualSimilarity/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: LPIPS metric
  doc_url: https://richzhang.github.io/PerceptualSimilarity/
  dev_url: https://github.com/richzhang/PerceptualSimilarity/

extra:
  recipe-maintainers:
    - oblute
    - mxr-conda
