{% set name = "lpips" %}
{% set version = "0.1.4" %}
{% set python_min = python_min|default("3.6") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/richzhang/PerceptualSimilarity/archive/v{{ version }}.tar.gz
  sha256: 6b42640be6c4a35e70930ce4f28c5fdb7584aeea2b03be2ffc3128be0cd57bca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pytorch  >=0.4.0
    - torchvision
    - scipy
    - scikit-image  >=0.13.0
    - opencv  >=2.4.11
    - matplotlib-base  >=1.5.1
    - tqdm  >=4.28.1
    - jupyter

test:
  imports:
    - lpips
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/richzhang/PerceptualSimilarity/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "LPIPS metric"
  doc_url: https://richzhang.github.io/PerceptualSimilarity/
  dev_url: https://github.com/richzhang/PerceptualSimilarity/

extra:
  recipe-maintainers:
    - oblute
    - mxr-conda
